Added support for CoinGecko's API
stepzen-dev/examples pull request #43
Opened 2022-09-01 05:27 UTC by helloitsm3

This PR contains support for CoinGecko's API.

Current API endpoints:

- Ping 
- Simple
- Coins
- Contract
- Asset Platforms
- Categories
- Exchanges
- Index
- Derivatives
- Exchange Rates
- Sesarch
- Trending
- Global
- Companies

@royderks do take a look at this.

2022-09-02 09:48 UTC, royderks requested changes
Overall looks good, thank you. Are there some interesting combinations between Coingecko REST endpoints that can be made using `@materializer`?

2022-09-02 09:48 UTC, royderks commented on with-coingecko/README.md
> +# StepZen Example: `with-firebase`
Could you update the title?

2022-09-02 09:48 UTC, royderks commented on with-coingecko/stepzen.config.json
> +  "endpoint": "api/loopy-alpaca"
Could you rename this to match the endpoint in the README?

2022-09-02 09:48 UTC, royderks commented on with-coingecko/index.graphql
> +      "types/assets.graphql"
typically we put all the generated `.graphql` files in a folder named after the data source. So `types` would be renamed to `coingecko`. I'll add this to the contributing guide

2022-09-02 09:48 UTC, royderks commented on with-coingecko/README.md
> +This project builds a GraphQL API connected to CoinGecko's API using StepZen. We will use the `@rest` directive to generate our GraphQL schema.
It would be nice to have a link to the Coingecko API docs here

2022-09-02 10:55 UTC, helloitsm3 commented
> Overall looks good, thank you. Are there some interesting combinations between Coingecko REST endpoints that can be made using `@materializer`?

I'll look into `@materializer` and see if I can use that

2022-09-09 15:18 UTC, royderks approved these changes

2022-09-09 15:20 UTC, merged