Add remix example
stepzen-dev/examples pull request #57
Opened 2022-10-12 10:47 UTC by tiluckdave

### Fixes #47 

StepZen example with https://remix.run

@royderks

2022-10-12 11:11 UTC, royderks requested changes

2022-10-12 11:11 UTC, royderks commented on with-remix/app/root.jsx
> +  const res = await fetch('https://graphql8f.stepzen.net/api/8f0ff813c3676d81a04a616ba555af0c/__graphql', requestOptions);
Could you include the setup instructions for the GraphQL API in the README?

2022-10-12 11:11 UTC, royderks commented on with-remix/README.md
> +- [Remix Docs](https://remix.run/docs)
We have a template for the README, it can be found in the file TEMPLATE.md

Please have a look and adjust accordingly :)

2022-10-12 12:15 UTC, tiluckdave commented
I have updated the README.md file

2022-10-12 12:19 UTC, royderks approved these changes

2022-10-12 12:20 UTC, merged

2022-10-13 09:03 UTC, tiluckdave commented
Hey, @royderks am I eligible for these goodies 
![image](https://user-images.githubusercontent.com/72644042/195553078-a96e5a72-5ade-4888-b539-f8bda1af1dbd.png)

2022-10-20 16:34 UTC, royderks commented
Yes @tiluckdave, Make sure to join our [Discord](https://discord.com/invite/9k2VdPn2FR) so we can help get the stickers over to you